name: Build Vue
on: 
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-18.04
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - run: |
        node --version
        npm install
        npm run build
        cd dist
        ln -s index.html 404.html
        git config --global user.email "CI@example.com"
        git config --global user.name "CI"
        git init
        git add -A
        git commit -m 'deploy'
        git push -f https://a-r-t:${{ secrets.GITHUB_TOKEN }}@github.com/a-r-t/Trello-Sprint-Plan-Parser.git master:gh-pages
      shell: bash