name: Build Vue
on: 
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'SER225-Intro-to-Software-Development'
        reponame: 'Trello-Sprint-Plan-Parser'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged